#!/usr/bin/env bash
# Copies the merged Mobile Order + NetNutrition menus built by duke_halal
# (src/build_nutriuni_menus.py -> outputs/nutriuni/) into assets/menu/ and
# regenerates assets/menu/registry.ts, because React Native can only bundle
# files referenced by static require() calls.
#
#   scripts/sync-menu-data.sh [path/to/duke_halal]   (default: ../../duke_halal)
set -euo pipefail
cd "$(dirname "$0")/.."

SOURCE="${1:-../../duke_halal}/outputs/nutriuni"
DEST="assets/menu"

if [[ ! -f "$SOURCE/index.json" ]]; then
  echo "No menu data at $SOURCE. Run 'python3 src/build_nutriuni_menus.py' in duke_halal first." >&2
  exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST/restaurants" "$DEST/icons"
cp "$SOURCE/index.json" "$DEST/"
cp "$SOURCE"/restaurants/*.json "$DEST/restaurants/"
cp "$SOURCE"/icons/* "$DEST/icons/" 2>/dev/null || true

node - "$DEST" <<'EOF'
const fs = require('fs');
const path = require('path');
const dest = process.argv[2];
const index = JSON.parse(fs.readFileSync(path.join(dest, 'index.json'), 'utf8'));
const quote = JSON.stringify;
const lines = [
  '// Generated by scripts/sync-menu-data.sh. Do not edit by hand.',
  "import type { MenuIndex, RestaurantMenu } from '@/services/menuTypes';",
  '',
  "export const menuIndex: MenuIndex = require('./index.json');",
  '',
  'export const restaurantFiles: Record<string, () => RestaurantMenu> = {',
  ...index.restaurants.map(r => `  ${quote(r.id)}: () => require(${quote('./restaurants/' + r.file)}),`),
  '};',
  '',
  'export const restaurantIcons: Record<string, number> = {',
  ...index.restaurants.filter(r => r.icon).map(r => `  ${quote(r.id)}: require(${quote('./icons/' + r.icon)}),`),
  '};',
  '',
];
fs.writeFileSync(path.join(dest, 'registry.ts'), lines.join('\n'));
const items = index.restaurants.reduce((sum, r) => sum + r.items, 0);
const withNutrition = index.restaurants.reduce((sum, r) => sum + r.with_nutrition, 0);
console.log(`Synced ${index.restaurants.length} restaurants (${withNutrition}/${items} items with nutrition), generated ${index.generated_at}`);
EOF
